### ISSUE TITLE
gRPC related issues?

### ISSUE THREAD

**Issue by sualehasif** [galexite/bazel-cpp-tools#1]
This used to work amazingly but recently, everything is failing. I am getting the following error:

```
INFO: Build option --action_env has changed, discarding analysis cache.
ERROR: /workspace/bazel_output_base/external/com_github_grpc_grpc/BUILD:915:16: in @bazel_vscode_compdb//:aspects.bzl%compilation_database_aspect aspect on cc_library rule @com_github_grpc_grpc//:gpr_codegen: 
Traceback (most recent call last):
        File "/workspace/bazel_output_base/external/bazel_vscode_compdb/aspects.bzl", line 312, column 48, in _compilation_database_aspect_impl
                compile_commands = _cc_compile_commands(ctx, target, feature_configuration, cc_toolchain)
        File "/workspace/bazel_output_base/external/bazel_vscode_compdb/aspects.bzl", line 157, column 73, in _cc_compile_commands
                compiler_options = cc_common.get_memory_inefficient_command_line(
Error in get_memory_inefficient_command_line: Invalid toolchain configuration: Cannot find variable named 'module_name'.
ERROR: Analysis of aspect '@bazel_vscode_compdb//:aspects.bzl%compilation_database_aspect of //schema:messenger_cc_grpc' failed; build aborted: Analysis of target '@com_github_grpc_grpc//:gpr_codegen' failed
INFO: Elapsed time: 1.189s
INFO: 0 processes.
INFO: Build Event Protocol files produced successfully.
```

**Comment by galexite** [comment]
Hey, thanks for reporting this issue! I forgot to change the URL from the Visual Studio marketplace, but this is the wrong repository for the VSCode extension. I'll move your issue over.
